### ISSUE TITLE
Concurrency problems after updating to v1.6.4

### ISSUE THREAD

**Issue by andremissaglia** [hamba/avro#141]
After updating to v1.6.4, some of our code that decoded avro data in parallel started to panic. I've reproduced the problem with this snippet:
```
var Schema = `{
    "type": "record",
    "name": "simple",
    "namespace": "org.hamba.avro",
    "fields" : [
        {"name": "a", "type": "long"},
        {"name": "b", "type": "string"}
    ]
}`

type SimpleRecord struct {
	A int64  `avro:"a"`
	B string `avro:"b"`
}

func main() {
	schema, err := avro.Parse(Schema)
	if err != nil {
		log.Fatal(err)
	}
	wg := &sync.WaitGroup{}
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go encodeAndDecode(schema, wg)
	}
	wg.Wait()

}
func encodeAndDecode(schema avro.Schema, wg *sync.WaitGroup) {
	defer wg.Done()
	in := SimpleRecord{A: 27, B: "foo"}

	data, err := avro.Marshal(schema, in)
	if err != nil {
		log.Fatal(err)
	}

	out := SimpleRecord{}
	err = avro.Unmarshal(schema, data, &out)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", out)
}

```

Until 1.6.3 (or after 1.6.4 with one goroutine) this code works. But now it fails with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4e9853]

goroutine 16 [running]:
github.com/hamba/avro.(*placeholderEncoder).Decode(0xc000066d20, 0x56e110, 0xc000122000)
        /mytest/vendor/github.com/hamba/avro/codec.go:171 +0x33
github.com/hamba/avro.(*Reader).ReadVal(0xc0000b0050, {0x56e110, 0xc000122000}, {0x510280, 0xc000094090})
        /mytest/vendor/github.com/hamba/avro/codec.go:63 +0x17d
github.com/hamba/avro.(*frozenConfig).Unmarshal(0xc000072140, {0x56e110, 0xc000122000}, {0xc00009c030, 0xc000094078, 0x0}, {0x510280, 0xc000094090})
        /mytest/vendor/github.com/hamba/avro/config.go:134 +0x6e
github.com/hamba/avro.Unmarshal(...)
        /mytest/vendor/github.com/hamba/avro/decoder.go:49
main.encodeAndDecode({0x56e110, 0xc000122000}, 0x0)
        /mytest/avrotest.go:49 +0x188
created by main.main
        /mytest/avrotest.go:34 +0x8c
```

It seems the problem was introduced with #139, but I'm not sure exactly why that makes the code thread-unsafe.

**Comment by nrwiersma** [comment]
Hi, thanks for reporting. I am looking into this now.

**Comment by nrwiersma** [comment]
I have reverted the changes in v1.6.4 and release v1.6.5 with the revert. I will have to take more time to implement recursive structs.

**Comment by defool** [comment]
Any progress to  implement recursive structs? @nrwiersma

**Comment by nrwiersma** [comment]
No, it is a fairly difficult problem to crack, without causing other issues.
