### ISSUE TITLE
MapUnionEncoder can not work correct

### ISSUE THREAD

**Issue by MashiroC** [hamba/avro#90]
I hava a schema:

```
{
			"namespace":"test.test",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"m1","type":["null",{"type":"map","values":"string"}]}
			]
		}
```

but if I use Marshal() to a map:

```go
rawSchema := `
{
			"namespace":"test.test",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"m1","type":["null",{"type":"map","values":"string"}]}
			]
		}`

	schema := avro.MustParse(rawSchema)

	b, err := avro.Marshal(schema, map[string]interface{}{
		"m1": map[string]interface{}{"map": map[string]string{"ASD": "asd"}},
	})
```

I got this:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x40fbe2]
```

if I edit the schema to :

```go
rawSchema := `
{
			"namespace":"test.test",
			"type":"record",
			"name":"In",
			"fields":[
				{"name":"m1","type":{"type":"map","values":"string"}}
			]
		}`
```

it is work.

I review the code, and find this bug is happen in codec_union.go : 144. reflect2.Ptr() is not get the correct ptr.

**Comment by nrwiersma** [comment]
Hi,

Thanks for reporting. Can you please provide a full example to reproduce the issue. Thanks.

**Comment by MashiroC** [comment]
> Hi,
> 
> Thanks for reporting. Can you please provide a full example to reproduce the issue. Thanks.

full example:

```go
func TestUnionMap(t *testing.T) {

	rawSchema := `
	{
				"namespace":"test.test",
				"type":"record",
				"name":"In",
				"fields":[
					{"name":"m1","type":["null",{"type":"map","values":"string"}]}
				]
			}`

	schema := avro.MustParse(rawSchema)

	b, err := avro.Marshal(schema, map[string]interface{}{
		"m1": map[string]interface{}{"map": map[string]string{"ASD": "asd"}},
	})

	if err != nil {
		panic(err)
	}

	fmt.Println(b)
}
```

after running:

```
=== RUN   TestUnionMap
--- FAIL: TestUnionMap (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x40fbe2]

goroutine 6 [running]:
testing.tRunner.func1.1(0x7cb760, 0xb695f0)
	C:/Go/src/testing/testing.go:941 +0x3d7
testing.tRunner.func1(0xc00011a900)
	C:/Go/src/testing/testing.go:944 +0x400
panic(0x7cb760, 0xb695f0)
	C:/Go/src/runtime/panic.go:967 +0x174
reflect.mapiterinit(0x7c88a0, 0x1, 0xc00003f300)
	C:/Go/src/runtime/map.go:1345 +0x5b
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
	C:/code/go/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/hamba/avro.(*mapEncoder).Encode(0xc000004fc0, 0xc000144630, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec_map.go:92 +0x6d
github.com/hamba/avro.(*mapUnionEncoder).Encode(0xc00003fc30, 0xc00006fbd0, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec_union.go:147 +0x2c7
github.com/hamba/avro.(*onePtrEncoder).Encode(0xc00003fc40, 0xc000144540, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec.go:151 +0x52
github.com/hamba/avro.(*Writer).WriteVal(0xc000048dc0, 0x8c64a0, 0xc000048d80, 0x7c86c0, 0xc000144540)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec.go:72 +0xdf
github.com/hamba/avro.(*interfaceEncoder).Encode(0xc000004f60, 0xc00011b168, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec_dynamic.go:46 +0x80
github.com/hamba/avro.(*recordMapEncoder).Encode(0xc000004f80, 0xc00006fe00, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec_record.go:311 +0x2cb
github.com/hamba/avro.(*onePtrEncoder).Encode(0xc00003fbe0, 0xc000144510, 0xc000048dc0)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec.go:151 +0x52
github.com/hamba/avro.(*Writer).WriteVal(0xc000048dc0, 0x8c6420, 0xc000050dc0, 0x7c86c0, 0xc000144510)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/codec.go:72 +0xdf
github.com/hamba/avro.(*frozenConfig).Marshal(0xc00004c1e0, 0x8c6420, 0xc000050dc0, 0x7c86c0, 0xc000144510, 0x1, 0xc000018638, 0x5089b6, 0x9ad2b0, 0x9ad310)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/config.go:103 +0x77
github.com/hamba/avro.Marshal(...)
	C:/code/go/pkg/mod/github.com/hamba/avro@v1.4.0/encoder.go:38
github.com/MashiroC/begonia/example/trace/sugar.TestUnionMap(0xc00011a900)
	C:/code/go/src/begonia/example/trace/sugar/avro_header_test.go:57 +0x1be
testing.tRunner(0xc00011a900, 0x853fe0)
	C:/Go/src/testing/testing.go:992 +0xe3
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:1043 +0x35e
```

and I find if I change github.com/modern-go/reflect2/unsafe_map.go : 110  func:

```go
func (type2 *UnsafeMapType) UnsafeIterate(obj unsafe.Pointer) MapIterator {
	return &UnsafeMapIterator{
		hiter:      mapiterinit(type2.rtype, *(*unsafe.Pointer)(obj)),
		pKeyRType:  type2.pKeyRType,
		pElemRType: type2.pElemRType,
	}
}
```

to:

```go
func (type2 *UnsafeMapType) UnsafeIterate(obj unsafe.Pointer) MapIterator {
	return &UnsafeMapIterator{
		hiter:      mapiterinit(type2.rtype, obj),
		pKeyRType:  type2.pKeyRType,
		pElemRType: type2.pElemRType,
	}
}
```

the example is work correct.

```
=== RUN   TestUnionMap
[2 1 16 6 97 115 100 6 97 115 100 0]
--- PASS: TestUnionMap (0.00s)
PASS
```

so this problem maybe another package modern-go/reflect2 's problem?

but i don't know if i edit reflect2's code, what problem or bug will happen.

**Comment by nrwiersma** [comment]
What version are you using, cause I cannot reproduce on the latest version?

**Comment by MashiroC** [comment]
> What version are you using, cause I cannot reproduce on the latest version?

v1.4.0 and modern-go/reflect2 v1.0.0

I try to upgrade latest version v1.5.4, it's work! thanks!
